### ISSUE TITLE
How are the whitelisted IP's calculated?

### ISSUE THREAD

**Issue by Gladuin** [CodeSwine/GTA5Online-Private_Public_Lobby#11]
Hey,

I'm rewriting this in PowerShell because I'm bored, but I how did you calculate the range of IP's that is whitelisted? I never used C# so I dont really know how you did it here...

Thanks a lot!

**Comment by Tmp341** [comment]
If you can finish it, i would like to check that out. 😃

**Comment by CodeSwine** [comment]
Hi

I'm terribly sorry for the late reply. I'm not sure if you need it but this might also help other people.

I keep a list of all IP addresses that need to be whitelisted. The point is, I don't really whitelist those IP addresses; I blacklist all other IP addresses. 

If 192.168.1.4 and 134.19.189.6 are whitelisted. I set the scope to 1.1.1.1-192.168.1.3, and then from 192.168.1.6-134.19.189.5 and then again from 134.19.189.7-255.255.255.255. This leaves me with the string `1.1.1.1-192.168.1.3,192.168.1.6-134.19.189.5,134.19.189.7-255.255.255.255` to set as the blacklisted scope. This scope excludes the whitelisted IPs.

If you meant how do you add 1 or subtract 1 from an IP address.

I first cast the string to an IP Address and get the Bytes from it. Then there's a check to see if the user's system has a different Byte structure, if `BitConverter.IsLittleEndian` is true then it means the Byte array needs to be reversed. Then I just cast it to an 32-bit unsigned integer and add or subtract 1 from the result. Then that result gets converted to an IP address. 

See https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby/blob/master/CodeSwine-Solo_Public_Lobby/CodeSwine-Solo_Public_Lobby/Helpers/RangeCalculator.cs#L23

It's not a foolproof system though ;)
