### ISSUE TITLE
Maintainers wanted.

### ISSUE THREAD

**Issue by CodeSwine** [CodeSwine/GTA5Online-Private_Public_Lobby#12]
I don't have time to support this project anymore and I'm looking for a maintainer. Preferably somebody with some C# knowledge and someone who likes simplicity.

**Comment by y2kmedman** [comment]
Being disabled I have a lot of time on my hands. I could learn the language that this is written in and possibly expand upon it. The ability to label each IP would be a nice feature. Also keeping the IP list in numerical and or alphabetical order would aid in searching and isolating unknown IPs/Gamertags from a packet sniffer search. I know you want to keep it simple but an in game overlay with a built-in and integrated packet sniffer would also be ideal. I will learn more about C#. I briefly learned how to do simple code in Junior high School on the Apple IIe. I also understand why your program does not do too well with sequential IPs such as "192.168.1.6" and "192.168.1.7".

**Comment by CodeSwine** [comment]
@all @y2kmedman  I'm very sory for my late reply and my absence. I'm still looking for maintainers and I'll actively check this repository now to get it done.
