### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by himselfego** [CodeSwine/GTA5Online-Private_Public_Lobby#2]
Are you planning to add IPv6 support?

**Comment by CodeSwine** [comment]
I'm having a busy month IRL, might take a look at it later.

**Comment by Column01** [comment]
It would need a GUI rework, and a few other things that would essentially mean a new program from what I see. I forked the repo and might tinker with it a bit in my spare time to see if I can make something like this,

**Comment by etshy** [comment]
waiting for IPv6 support too.

**Comment by CodeSwine** [comment]
Added by @Elec0 thanks!
