### ISSUE TITLE
How exactly does this work?

### ISSUE THREAD

**Issue by ShaunTheQuietGamer** [CodeSwine/GTA5Online-Private_Public_Lobby#24]
I'm running GTAO on Linux through proton, and I'm trying to figure out how this works so that i can manually set it up with a Linux firewall, as this program cannot run in proton. Can I get a bit of an explanation as to what I would need to do / what this program does to create a private session for me and a few friends?

EDIT: Clarification

**Comment by Sokoloft** [comment]
> I'm running GTAO on Linux through proton, and I'm trying to figure out how this works so that i can manually set it up with a Linux firewall, as this program cannot run in proton. Can I get a bit of an explanation as to what I would need to do / what this program does to create a private session for me and a few friends?
> 
> EDIT: Clarification

The application blocks UDP port 6672 inbound and outbound. Only allows certain ip's to go through. In windows firewall it's under scope and remote ip address's. Idk how you'd do that through UFW or whatever firewall you use. 

In windows, pausing the task and resuming it is the best to get your own session. Then once your friends connect, activate the blocked ports and anyone else connected to the session that doesn't have their ip listed will drop.

I edited this app a while ago and added my own functionality to do so. Should fork the project and upload my version. It's before the ipv6 update.

Best of luck!
