### ISSUE TITLE
After trying out this piece of software, I can no longer connect and play online with other players.

### ISSUE THREAD

**Issue by Razatop** [CodeSwine/GTA5Online-Private_Public_Lobby#31]
Friends cant join and I can't join players online. It gets stuck as "Getting Session Details." I've turned off my firewall, deleted firewall settings pertaining to the software. Restarted my PC, and reset firewall to default. How the hell can I fix this issue?

**Comment by Peshmerga1990** [comment]
> 
> 
> Friends cant join and I can't join players online. It gets stuck as "Getting Session Details." I've turned off my firewall, deleted firewall settings pertaining to the software. Restarted my PC, and reset firewall to default. How the hell can I fix this issue?

Did you try  re-installing GTA ?

**Comment by Razatop** [comment]
I disabled my public firewall and it ended up working again, gonna do a full firewall reset since the last public release seems to have fucked it. It's not a GTA problem. It's an issue with the software.

**Comment by CodeSwine** [comment]
Run the following commands in cmd as administrator to forcibly delete the rules from your firewall if they still exist:
`netsh advfirewall firewall delete rule name=”GTA5 CodeSwine - Private Public Lobby Inbound” dir=in`
`netsh advfirewall firewall delete rule name=”GTA5 CodeSwine - Private Public Lobby Outbound” dir=out`

**Comment by Elec0** [comment]
> I disabled my public firewall and it ended up working again, gonna do a full firewall reset since the last public release seems to have fucked it. It's not a GTA problem. It's an issue with the software.

It wasn't the latest release, nothing changed in the firewall settings.
