### ISSUE TITLE
whitelisting not working?

### ISSUE THREAD

**Issue by 0utlierrr** [CodeSwine/GTA5Online-Private_Public_Lobby#32]
Added friend's IP, followed instructions, but he gets kicked as soon as I turn the firewall back on.

**Comment by 0utlierrr** [comment]
Wanted to add that I'm using a vpn. not sure if that matters. Definitely ran as admin and followed the 5 steps exactly. Let me know if you have any advice. Thanks.

**Comment by Peshmerga1990** [comment]
> 
> 
> Wanted to add that I'm using a vpn. not sure if that matters. Definitely ran as admin and followed the 5 steps exactly. Let me know if you have any advice. Thanks.

The app isn't working at the moment because of GTA's latest update, Rockstar has made some changes to their network in GTA Online which nerved the app, the developers are currently busy with finding a solution for it.

**Comment by 0utlierrr** [comment]
Thanks for the reply!
