### ISSUE TITLE
how can I get friends ip?

### ISSUE THREAD

**Issue by darknessjs** [CodeSwine/GTA5Online-Private_Public_Lobby#4]
We use vpn or other services.So we can't get true ip by the tool.
When I use a vpn and vpn's ipaddress is xxx and join this xxx in whitelist.It's work.
But I can't find my ipaddress in my partner's computer by wireshark.
And my own vpn is slowly and it can't give my partner .
Others vpn can't get their ip.
So i want to know how to get true ip.or some idea to get my friends' ip?

**Comment by darknessjs** [comment]
If i connect my friends game.We don't need know vpn's ipaddress because we are using p2p to connect each other?

**Comment by CodeSwine** [comment]
You don't need anyone's true IP, a decent vpn should cover your entire network and even handle peer-to-peer connections. Your public IPv4 will be that of your vpn and will be used for P2P. 

Also you can't wireshark and sniff public internet, only your local Wifi/Ethernet connection, so unless your friend is at your house you won't find him.
