### ISSUE TITLE
after active rules can't connect STEAM

### ISSUE THREAD

**Issue by lililalaTW** [CodeSwine/GTA5Online-Private_Public_Lobby#43]
Win11 
after active rules can't connect STEAM
need to delete steam firewall settings to rejoin

**Comment by Peshmerga1990** [comment]
> Win11 after active rules can't connect STEAM need to delete steam firewall settings to rejoin

The app hasn't been updated for a long time, it's not 100% compatible with Windows 11, it might cause some issues

**Comment by Elec0** [comment]
> Win11 after active rules can't connect STEAM need to delete steam firewall settings to rejoin

I will point you to [the last commit.](https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby/commit/04cd149829fa6d25b2321f8b87e52385ebed19e0) Yeah, it doesn't work.
