### ISSUE TITLE
Alternative port blocking method

### ISSUE THREAD

**Issue by jacklul** [CodeSwine/GTA5Online-Private_Public_Lobby#6]
Would it be a problem to add a secondary mode where you block remote and local (depending on rule) ports - "6672, 61455, 61457, 61456, 61458" ?

It seems the method you're using (blocking one local port) does not work for many people so it's kinda outdated.

**Comment by Tmp341** [comment]
Actually you should block remote ports. That's what i've been blocking. And it was working for me a couple of months ago (i have an antivirus app with a built in firewall, so i couldn't make it work with Windows' , i'm using it's firewall without a problem).
