### ISSUE TITLE
Activating the rules after friends joining causes me to be kicked

### ISSUE THREAD

**Issue by Column01** [CodeSwine/GTA5Online-Private_Public_Lobby#8]
Whenever I get my friends to join my lobby, and then activate the rules again, it kicks me from the lobby. Tried multiple times with different friends and every single time I get kicked. I have added some of their IPs but I would like to be able to use this with randos where I cannot get their IP. Maybe rockstar changed how online connections work?

Version: 1.0.1
Running as Admin
GTA Online Version: 1.44

**Comment by CodeSwine** [comment]
Hi @Column01 

Apologies for the late reply, I haven't worked on the tool in the past year. I'm required to ask you this question, but did you add your own IP to the tool? (you shouldn't, but could try)

GTA 5 connectivity can be complex. Maybe you're just not able to host a pool of players because you're not 'connectable' enough. Same way some people can join a Call of Duty lobby but can't host one. I know we're blocking one on purpuse though.

Did you disable IPv6? Any error file generated by the tool? Did your friends try to host one?

Kinds regards
CodeSwine

**Comment by Column01** [comment]
Hey @CodeSwine,
The error file that was generated had errors that were really old and were because of a bad IP address. My NAT Type is open, and I have my friends whitelisted in the tool, but not my own IP. It works if they join and then I enable the rules, but they cannot join with them on nor can they stay connected if I do not have them added to the list of IPs. I am definitely the host because when I throttle my connection my friends begin to lag on the server. I have not disabled IPv6, and the address that shows up in the program is my IPv6 address. My friend tried to host a lobby with the same result, randoms without whitelisted IPs get kicked from the lobby when rules are enabled. I've also noticed that sometimes (infrequent but repeatable after many days of playtime with this program) my friends will also get kicked from the lobby if I turn them on even while they are whitelisted. I then have to restart the program for it to not kick them next time I enable the rules.
I hope this is enough info
Thanks again,
Colin

**Comment by Column01** [comment]
I discovered a flaw with it. Since you are using the site http://icanhazip.com/ in your code to pull the user's public IP, their update to allow IPv6 connections has made it so it shows IPv6 by default for people who have both IPv4 and IPv6. A fix for it would be to swap to this URL http://ipv4.icanhazip.com/ in the code to pull the IPv4 address. This might also have something to do with my issue but I am not certain as I have only skimmed the code so far.

**Comment by CodeSwine** [comment]
> but they cannot join with them on nor can they stay connected if I do not have them added to the list of IPs. 
This is a flaw I cannot circumvent. You can't just host a solo lobby, close it and then invite your friends as far as I know. You need to join a lobby, enable the rules and wait for everyone to get kicked. Then you disable and invite. When everybody is present, enable the rules again.

That's how I've always used the tool. Thanks for your PR. I'll make a release soon.

**Comment by wrentrillogy** [comment]
The tool works perfect. I use it to this day. Simply launch Gta 5 get into a session launch tool activate rules. Everyone gets kicked deactivate rules. Invite your Whitelist into the lobby after they join activate rules. Again I use this daily and have no issue at all!

**Comment by Column01** [comment]
@wrentrillogy You clearly did not read my message.
It appears its working like it used too now so Rockshit obviously changed something. Closing the issue
